repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: |
          ruff check --select I --fix
          ruff format .
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
